app_name = "maldives_gst_setup"
app_title = "Maldives Gst Setup"
app_publisher = "Your Name"
app_description = "GST setup and automation for Maldives"
app_icon = "octicon octicon-file-directory"
app_color = "blue"
app_email = "you@example.com"
app_license = "MIT"
